import esbuild from 'esbuild';
import process from 'process';
import builtins from 'builtin-modules';
import copy from 'esbuild-plugin-copy';
import { replace } from 'esbuild-plugin-replace';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtins,
  ],
  format: 'cjs',
  target: 'es2018',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'dist/main.js',
  plugins: [
    replace({
      values: {
        __DEV_MODE__: !prod,
      },
      exclude: /.*utils.ts/,
    }),
    copy({
      resolveFrom: 'cwd',
      assets: [
        {
          from: ['./manifest.json'],
          to: ['./dist/manifest.json'],
        },
        {
          from: ['./styles.css'],
          to: ['./dist/styles.css'],
        },
      ],
      watch: true,
    }),
  ],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
